# Generated by Django 5.0.1 on 2024-01-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='proudcts',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
