# Generated by Django 5.0.1 on 2024-01-31 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_seller_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.BigIntegerField(default=9847630534, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number.', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='tikathali', max_length=255),
            preserve_default=False,
        ),
    ]
