# Generated by Django 5.0.1 on 2024-02-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_contact_number_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='Amit', max_length=100),
            preserve_default=False,
        ),
    ]
